/***************************************************************************
 *   Copyright (c) 2008   Art Tevs                                         *
 *                                                                         *
 *   This library is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU Lesser General Public License as        *
 *   published by the Free Software Foundation; either version 3 of        *
 *   the License, or (at your option) any later version.                   *
 *                                                                         *
 *   This library is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU Lesse General Public License for more details.                    *
 *                                                                         *
 *   The full license is in LICENSE file included with this distribution.  *
 ***************************************************************************/

/****************************************************************************
 * THIS FILE IS AUTOGENERATED BY CMAKE. DO NOT EDIT!
 ****************************************************************************/

/* Changes to the configuration reflected here can be made with ccmake on
 * unix or with cmake-gui on windows. Alternatively you can use cmake's -D
 * or -P switches to set some configuration values at cmake configuration time.
 */

#ifndef OSGPPU_CONFIG
#define OSGPPU_CONFIG 1

/* #undef CUDA_FOUND */

#endif
